# Defines the GitHub Actions workflow name as Playwright Tests.
name: Playwright Tests

# Triggers the workflow whenever code is pushed or a pull request is made to the main or master branches.
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

# Defines a job named test that will run the automation tasks.
jobs:
  test:
    runs-on: ubuntu-latest
    env:
      # Environment variables required for the Playwright tests
      BASE_URL: ${{ secrets.BASE_URL }}
      WORDPRESS_URL: ${{ secrets.WORDPRESS_URL }}
      WORDPRESS_USERNAME: ${{ secrets.WORDPRESS_USERNAME }}
      WORDPRESS_PASSWORD: ${{ secrets.WORDPRESS_PASSWORD }}
      GOOGLE_SHEET_URL: ${{ secrets.GOOGLE_SHEET_URL }}
      TABLE_TITLE: ${{ secrets.TABLE_TITLE }}
      TABLE_DESCRIPTION: ${{ secrets.TABLE_DESCRIPTION }}
      PAGE_TITLE: ${{ secrets.PAGE_TITLE }}
      ROWS_PER_PAGE: ${{ secrets.ROWS_PER_PAGE }}
      TABLE_HEIGHT: ${{ secrets.TABLE_HEIGHT }}
      WOOCOMMERCE_BASE_URL: ${{ secrets.WOOCOMMERCE_BASE_URL }}
      WOOCOMMERCE_ADMIN_URL: ${{ secrets.WOOCOMMERCE_ADMIN_URL }}
      WOOCOMMERCE_ADMIN_USERNAME: ${{ secrets.WOOCOMMERCE_ADMIN_USERNAME }}
      WOOCOMMERCE_ADMIN_PASSWORD: ${{ secrets.WOOCOMMERCE_ADMIN_PASSWORD }}
      WOOCOMMERCE_CUSTOMER_NAME: ${{ secrets.WOOCOMMERCE_CUSTOMER_NAME }}
      WOOCOMMERCE_CUSTOMER_USERNAME: ${{ secrets.WOOCOMMERCE_CUSTOMER_USERNAME }}
      WOOCOMMERCE_CUSTOMER_PASSWORD: ${{ secrets.WOOCOMMERCE_CUSTOMER_PASSWORD }}
    steps:
      # Step 1: Checkout code pulls the project’s source code from GitHub into the runner.
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Installs the specified Node.js version (LTS) required for running the project.
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      # Step 3: Installs all project dependencies listed in the package-lock.json using npm ci.
      - name: Install dependencies
        run: npm ci

      # Step 4: Install Playwright Browsers — Downloads and installs all necessary browser binaries and dependencies for Playwright.
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      # Executes all Playwright test cases in parallel across supported browsers.
      - name: Run Playwright tests
        run: npx playwright test

      # Uploads the generated Playwright test report as an artifact to GitHub with a 30-day retention period.
      - name: Upload Playwright Report
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30 
